# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html



security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        #SymfonyFirstApp\Entity\User: plaintext
        SymfonyFirstApp\Entity\User:
            algorithm: bcrypt
            cost: 12





    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]





    providers:
        users:
             entity: { class: SymfonyFirstApp:User, property: username }
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }




    firewalls:
       default:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /login
            
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER } #, requires_channel: https